# Generated by Django 6.0 on 2025-12-22 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена со скидкой')),
                ('care_difficulty', models.CharField(choices=[('easy', 'Легкий'), ('medium', 'Средний'), ('hard', 'Сложный')], default='medium', max_length=10, verbose_name='Сложность ухода')),
                ('light_requirements', models.CharField(max_length=100, verbose_name='Требования к свету')),
                ('watering_frequency', models.CharField(max_length=100, verbose_name='Частота полива')),
                ('height', models.CharField(blank=True, max_length=50, verbose_name='Высота')),
                ('pot_diameter', models.CharField(blank=True, max_length=50, verbose_name='Диаметр горшка')),
                ('main_image', models.ImageField(upload_to='plants/', verbose_name='Основное изображение')),
                ('additional_images', models.JSONField(blank=True, default=list, verbose_name='Дополнительные изображения')),
                ('in_stock', models.BooleanField(default=True, verbose_name='В наличии')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендуемый')),
                ('is_new', models.BooleanField(default=False, verbose_name='Новинка')),
                ('rating', models.FloatField(default=0.0, verbose_name='Рейтинг')),
                ('review_count', models.IntegerField(default=0, verbose_name='Количество отзывов')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plants', to='shop.category')),
            ],
            options={
                'verbose_name': 'Растение',
                'verbose_name_plural': 'Растения',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name', 'category'], name='shop_plant_name_9e1c8c_idx'), models.Index(fields=['price'], name='shop_plant_price_ba28d4_idx'), models.Index(fields=['is_featured'], name='shop_plant_is_feat_02586a_idx')],
            },
        ),
    ]
