# Generated by Django 6.0 on 2025-12-26 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='agreements',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='username',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='agree_offer',
            field=models.BooleanField(default=False, verbose_name='Согласие с офертой'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='agree_personal',
            field=models.BooleanField(default=False, verbose_name='Согласие на обработку ПД'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='agree_privacy',
            field=models.BooleanField(default=False, verbose_name='Согласие с политикой конфиденциальности'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('standard', 'Стандарт'), ('blocked', 'Заблокирован'), ('junior_admin', 'Младший администратор'), ('senior_admin', 'Старший администратор')], default='standard', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Отчество'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(max_length=50, verbose_name='Никнейм'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
    ]
